feat(api): wrapping promises with Effect
candlefinance/oss pull request #42
Opened 2024-06-27 04:11 UTC by nikwotton

2024-06-27 04:28 UTC, liambutler-lawrence commented on packages/npm/financekit/ios/Financekit.swift
> +        if #available(iOS 17.4, *) {
Suggestion to use `guard` instead of `if`, it lets you put the error handling at the top, and avoid indent hell

2024-06-27 04:36 UTC, nikwotton commented on packages/npm/financekit/ios/Financekit.swift
> +        if #available(iOS 17.4, *) {
I couldn't figure out how to do this before and gave up - apparently it's easier than I was making it out to be 😓

2024-06-27 04:44 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +const Financekit: Record<
```suggestion
const financeKitNativeModule: Record<
```

2024-06-27 04:45 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +const Financekit: Record<
This is just an object at the end of the day, it's not a type/schema/class.

2024-06-29 02:51 UTC, liambutler-lawrence commented on packages/npm/financekit/ios/Financekit.swift
> +private let CODE_QUERY_INVALID: String = "@candlefinance.financekit.query_invalid"
This should be inferred in Swift

2024-07-01 03:01 UTC, nikwotton commented on packages/npm/financekit/ios/Financekit.swift
> +private let CODE_QUERY_INVALID: String = "@candlefinance.financekit.query_invalid"
Removed

2024-07-01 04:12 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +    backingError: S.Any,
I see this property is set in `makeError` but what would set it in the native/bridge layer? 🤔

2024-07-01 04:14 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +const makeError = <CODE extends String & FinancekitError['code']>(
```suggestion
const makeError = <Code extends String & FinancekitError['code']>(
```

TS generics are conventionally either `A`, `T` etc or upper camel case eg `Code`

2024-07-01 04:15 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +    // TODO: Can this be done without a hard cast?
Not sure why the cast would be necessary, what happens when you omit it?

2024-07-01 04:20 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +    | '@candlefinance.financekit.unknown_parsing_error'
2 thoughts on this:
- TS uses "decoding" more than "parsing", especially when there's no string transformation involved (as is the case for the invalid error scenario)
- You're returning this error in two different scenarios that should be distinguished, I would prob call them `.invalid_error_response_schema` and `.invalid_response_schema` respectively

2024-07-01 04:20 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +    | '@candlefinance.financekit.unknown_parsing_error'
(this applies to all the functions in this file)

2024-07-01 04:32 UTC, liambutler-lawrence commented on packages/npm/financekit/ios/Financekit.swift
> +            } catch let error as UnknownCurrentBalanceTypeError {
I agree with what you're trying to accomplish with this change (eliminating impossible code paths) but Swift actually has syntax for this that would work with the original enum: 
```suggestion
            } catch FinancekitError.unknownCurrentBalanceType(let message). {
```

2024-07-01 04:35 UTC, liambutler-lawrence requested changes
Lg overall, couple suggestions, biggest question is if you were able to test any of this in the example app (at least verifying our assumptions in the error scenario around error propagation, error types, decoding logic etc, since obviously we can't test happy path). I would suggest committing whatever code you use(d) to test in the example app too.

2024-07-01 23:22 UTC, nikwotton commented on packages/npm/financekit/ios/Financekit.swift
> +            } catch let error as UnknownCurrentBalanceTypeError {
I think mostly this change was due to not seeing a point in having an enum for all possible errors when functions can only return one or two of them. Especially when that enum isn't exposed to end users or used outside of swift.

2024-07-01 23:55 UTC, liambutler-lawrence commented on packages/npm/financekit/example/src/App.tsx
> +      <Text>accounts Result: {accountsResult}</Text>
```suggestion
      <Text>Accounts Result: {accountsResult}</Text>
```

2024-07-01 23:56 UTC, liambutler-lawrence commented on packages/npm/financekit/example/src/global.js
> +global.TextEncoder = require('text-encoding').TextEncoder
You should only have to use either `import` or `require`, not both.

2024-07-01 23:57 UTC, liambutler-lawrence commented on packages/npm/financekit/example/src/global.js
> +global.TextEncoder = require('text-encoding').TextEncoder
This should also be a .ts file 😂

2024-07-01 23:59 UTC, liambutler-lawrence commented on packages/npm/financekit/example/src/App.tsx
> +  React.useEffect(() => {
TBH main ideas for simplifying this is just make a helper function that abstracts this pipe

2024-07-01 23:59 UTC, liambutler-lawrence commented on packages/npm/financekit/example/src/App.tsx
> +        onSuccess: (a) => 'Success:' + a,
```suggestion
        onSuccess: (a) => 'Success: ' + a,
```
for all

2024-07-02 00:00 UTC, liambutler-lawrence commented on packages/npm/financekit/src/discrimination_utils.tsx
> +export const oLiftRefinement = <A, B extends A>(
I'd rename this file to just `utils.ts`, it's not just discrimination stuff + doesn't have any React code so doesn't need to be `.tsx`

2024-07-02 00:01 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +export const uuid = S.UUID.pipe(S.brand('CNDL_UUID'))
```suggestion
export const S_CNDL_UUID = S.UUID.pipe(S.brand('CNDL_UUID'))
```
Should at least start with an uppercase letter like the other schemas. My suggestion is just to match with Candle repo standards

2024-07-02 00:02 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +export const int = S.Int.pipe(S.brand('CNDL_INT'))
```suggestion
export const S_CNDL_Int = S.Int.pipe(S.brand('CNDL_Int'))
```
same as above + in the brands I usually just add the `CNDL_` prefix to whatever it is, I don't uppercase everything

2024-07-02 00:04 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +    message: JSON.stringify(error),
```suggestion
    message: error.message,
```
I think if for some reason our decoding ever fails here, better to just copy the human-readable message of the underlying error rather then make it an unreadable mess haha

2024-07-02 00:08 UTC, liambutler-lawrence commented on packages/npm/financekit/src/index.tsx
> +        },
Debugging code?
```suggestion
```

2024-07-02 00:10 UTC, liambutler-lawrence approved these changes

2024-07-02 00:11 UTC, liambutler-lawrence requested changes
Mostly typos :)

2024-07-02 00:59 UTC, nikwotton commented on packages/npm/financekit/example/src/App.tsx
> +  React.useEffect(() => {
Took a stab at it, let me know if you find a better approach

2024-07-02 01:00 UTC, nikwotton commented on packages/npm/financekit/src/index.tsx
> +export const uuid = S.UUID.pipe(S.brand('CNDL_UUID'))
which you haven't merge yet...care to share what they are?

2024-07-02 01:37 UTC, liambutler-lawrence commented on packages/npm/financekit/example/src/App.tsx
> +import './global.ts'
This should be imported at the very top so that it loads the polyfill before any other code loads/runs.

You can add an extra new line between imports so that it stays at the top.

2024-07-02 01:39 UTC, liambutler-lawrence commented on packages/npm/financekit/example/src/App.tsx
> +  React.useEffect(() => {
Lgtm!

2024-07-02 02:52 UTC, liambutler-lawrence approved these changes

2024-07-02 03:02 UTC, merged